# Sử dụng Node.js phiên bản 20 trên Alpine Linux
FROM node:20-alpine

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép các file cần thiết
COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY ecosystem.config.js .
COPY .env.development .
COPY ./src ./src
COPY ./openapi ./openapi

# Cài đặt Python (nếu cần cho các gói npm)
RUN apk add --no-cache python3
RUN apk add --no-cache ffmpeg


# Cài đặt pm2 toàn cục và các module cần thiết
RUN npm install pm2 -g
RUN npm install

# Build ứng dụng
RUN npm run build

# Mở cổng 8080
EXPOSE 8080

# Khởi chạy ứng dụng sử dụng PM2
CMD ["pm2-runtime", "start", "ecosystem.config.js"]
