openapi: 3.0.3
info:
  title: Twitter Clone
  description: Project Twitter Clone by Nguyen Quang Thuan
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: APIs user
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Login
      description: Log in to the system
      operationId: login
      requestBody:
        description: Information login
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
        required: true
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationSuccess'
        '422':
          description: Validation exception
  /users/me:
    get:
      tags:
        - Me
      summary: Get information me
      description: Get information me
      operationId: getMe
      security:
        - BearerAuth: []

      responses:
        default:
          description: Get my profile success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Get my profile success
                  result:
                    $ref: '#/components/schemas/User'
