name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: echo "${{secrets.TWITTER_ENV_PRODUCTION}}" > .env.production

      - name: Build the Docker image
        run: docker build --progress=plain -t thuannqt/twitter:v5 .

      - name: Login to Docker hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Push the Docker image
        run: docker push thuannqt/twitter:v5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.HOST_USERNAME}}
          password: ${{secrets.HOST_PASSWORD}}
          port: ${{secrets.PORT}}
          script: |
            docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
            docker pull thuannqt/twitter:v5
            docker stop twitter-clone
            docker rm twitter-clone
            docker run -dp 8002:8002 --name twitter-clone -v /uploads:/app/uploads thuannqt/twitter:v5
