name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: 'Create env file'
        run: echo "${{secrets.TWITTER_ENV_PRODUCTION}}" > .env.production

      - name: Build the Docker image
        run: docker build --progress=plain -t thuannqt/twitter:v5 .

      - name: Login to Docker hub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Push the Docker image
        run: docker push thuannqt/twitter:v5
